<<<<<<< HEAD
#ifndef UNIFORM_LOCATIONS_GLSL
#define UNIFORM_LOCATIONS_GLSL

#define VERTEX_ATTRIB_LOCATION 0
#define NORMAL_ATTRIB_LOCATION 1
#define TEXTURE_ATTRIB_LOCATION 2

#define UNIFORM_MATRIX_LOCATION 0
#define UNIFORM_TEXTURE_LOCATION 1

#define MATRIX_BUFFER_BINDING 0

#endif
=======
#ifndef UNIFORM_LOCATIONS_GLSL
#define UNIFORM_LOCATIONS_GLSL

#define VERTEX_ATTRIB_LOCATION 0
#define NORMAL_ATTRIB_LOCATION 1
#define TEXTURE_ATTRIB_LOCATION 2

#define UNIFORM_MATRIX_LOCATION 0
#define UNIFORM_TEXTURE_LOCATION 1

#define MATRIX_BUFFER_BINDING 0

#endif
>>>>>>> 17e2c9f0015b84508c0980fb762a587738dc55ae
