<<<<<<< HEAD
#ifndef UNIFORM_LOCATIONS_GLSL
#define UNIFORM_LOCATIONS_GLSL

#define VERTEX_ATTRIB_LOCATION 0
#define NORMAL_ATTRIB_LOCATION 1
#define TEXTURE_ATTRIB_LOCATION 2

#define MATRIX_BUFFER_BINDING 0
#define LIGHT_BUFFER_BINDING 1
#define IMAGE_TEXTURE_BINDING 2

=======
#ifndef UNIFORM_LOCATIONS_GLSL
#define UNIFORM_LOCATIONS_GLSL

#define VERTEX_ATTRIB_LOCATION 0
#define NORMAL_ATTRIB_LOCATION 1
#define TEXTURE_ATTRIB_LOCATION 2

#define MATRIX_BUFFER_BINDING 0
#define LIGHT_BUFFER_BINDING 1
#define IMAGE_TEXTURE_BINDING 2

>>>>>>> 17e2c9f0015b84508c0980fb762a587738dc55ae
#endif